name: Workflow Coordinator

on:
  push:
    branches: [master]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: xshop
          MYSQL_USER: nova
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host 127.0.0.1 --user root --password=password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Setup Virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Setup Variables Env
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
          echo "DATABASE_ENGINE=django.db.backends.mysql" >> .env
          echo "DATABASE_NAME=xshop" >> .env
          echo "DATABASE_USER=nova" >> .env
          echo "DATABASE_PASSWORD=password" >> .env
          echo "DATABASE_HOST=127.0.0.1" >> .env
          echo "DATABASE_PORT=3306" >> .env

      - name: Wait for MySQL
        run: |
          timeout=60
          counter=0
          echo "Waiting for MySQL..."
          while ! mysqladmin ping -h 127.0.0.1 -P 3306 -u nova --password=password --silent; do
            if [ $counter -gt $timeout ]; then
              echo "MySQL connection timed out!"
              exit 1
            fi
            echo "MySQL not ready yet. Waiting..."
            sleep 3
            counter=$((counter+3))
          done
          echo "MySQL is up and running!"

      - name: Grant Database Privileges
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e "GRANT ALL PRIVILEGES ON *.* TO 'nova'@'%'; FLUSH PRIVILEGES;"

      - name: Run migrations
        run: pipenv run python manage.py migrate

      - name: Run tests
        run: pipenv run python manage.py test tests

  deploy-client:
    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Preset Image Name
        run: echo "FE_IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/feshop:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ env.FE_IMAGE_URL }}
          build-args: |
            VITE_API_ROOT=${{ vars.VITE_API_ROOT }}
            VITE_STRIPE_PK=${{ vars.VITE_STRIPE_PK }}
            VITE_FLOWISE_CHATFLOW_ID=${{ vars.VITE_FLOWISE_CHATFLOW_ID }}
            VITE_FLOWISE_API_HOST=${{ vars.VITE_FLOWISE_API_HOST }}

      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.FE_APP_NAME }}"
          token: "${{ secrets.FE_APP_TOKEN }}"
          image: ${{ env.FE_IMAGE_URL }}

  deploy-backend:
    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Preset Image Name
        run: echo "BE_IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/beshop:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.BE_IMAGE_URL }}

      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.BE_APP_NAME }}"
          token: "${{ secrets.BE_APP_TOKEN }}"
          image: ${{ env.BE_IMAGE_URL }}
