name: execute tests
run-name: tests execution
on:
  pull_request:
    branches: [master]
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Setup Variables Env
        run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env

      - name: Run migrations
        run: uv run python manage.py migrate

      - name: Run tests
        run: uv run python manage.py test tests
