name: execute tests
run-name: tests execution
on:
  pull_request:
    branches: [master]
jobs:
  echo_header:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Header
        run: echo "Running Tests"

  run_tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: lumiere
          MYSQL_USER: lumiere
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host 127.0.0.1 --user root --password=password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Setup Variables Env
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
          echo "DATABASE_ENGINE=django.db.backends.mysql" >> .env
          echo "DATABASE_NAME=lumiere" >> .env
          echo "DATABASE_USER=lumiere" >> .env
          echo "DATABASE_PASSWORD=password" >> .env
          echo "DATABASE_HOST=127.0.0.1" >> .env
          echo "DATABASE_PORT=3306" >> .env

      - name: Wait for MySQL
        run: |
          timeout=60
          counter=0
          echo "Waiting for MySQL..."
          while ! mysqladmin ping -h 127.0.0.1 -P 3306 -u lumiere --password=password --silent; do
            if [ $counter -gt $timeout ]; then
              echo "MySQL connection timed out!"
              exit 1
            fi
            echo "MySQL not ready yet. Waiting..."
            sleep 3
            counter=$((counter+3))
          done
          echo "MySQL is up and running!"

      - name: Grant Database Privileges
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e "GRANT ALL PRIVILEGES ON *.* TO 'lumiere'@'%'; FLUSH PRIVILEGES;"

      - name: Run migrations
        run: uv run python manage.py migrate

      - name: Run tests
        run: uv run python manage.py test tests
